// mutations.js
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_PASS = 'SET_USER_PASS';
export const SET_USER_CODE = 'SET_USER_CODE';
export const SET_LOAD_STATES = 'SET_LOAD_STATES';
export const SET_SCHEDULE = 'SET_SCHEDULE';
export const SET_CUSTOMERS_LIST = 'SET_CUSTOMERS_LIST';
export const SET_SERVICES_LIST = 'SET_SERVICES_LIST';
export const SET_SUPPLIERS_LIST = 'SET_SUPPLIERS_LIST';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const SET_SERVICE = 'SET_SERVICE';
export const SET_SUPPLIER = 'SET_SUPPLIER';